version: "3.7"
services:
  go-docker-image:
    build: ./
    ports:
      - '80:80'
    volumes:
      - ./:/app

  database:
    image: 'mongo'
    container_name: 'mongo-container'
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

    